---
name: Checks

on: [push]

jobs: 
  tes-lint:
   name: Test and Lint
   runs-on: ubuntu-20.04
   steps:
     - name: Login to docker hub
       uses: docker/login-action@v1
       with:
         username: joud1993
         password: hamada8asus
     - name: Checkout
       uses: actions/checkout@v2
     - name: Test
       run: docker-compose run --rm app sh -c "python manage.py test"  